//
// THIS FILE IS AUTO-GENERATED
//
// Do not modify this file directly. All changes will be lost when the code is regenerated.
// To make changes to this vector type, modify the SourceGenerator project and regenerate the code.
//
// Generated by: Prowl.Vector's SourceGenerator Console Application
// Date: 2025-05-14 11:12:59
//

using System;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Collections.Generic;
using System.Linq;

namespace Prowl.Vector
{
    /// <summary>
    /// Represents a 4-component vector using double precision.
    /// </summary>
    [System.Serializable]
    public partial struct Double4 : IEquatable<Double4>, IFormattable
    {
        public double X, Y, Z, W;

        // --- Constructors ---
        /// <summary>Initializes all components to a single scalar value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double scalar) : this(scalar, scalar, scalar, scalar) { }

        /// <summary>Initializes with specified component values.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double x, double y, double z, double w)
        {
            X = x;
            Y = y;
            Z = z;
            W = w;
        }

        /// <summary>Initializes by copying components from another Double4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Double4 v) : this(v.X, v.Y, v.Z, v.W) { }

        /// <summary>Initializes from an array.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double[] array)
        {
            if (array == null) throw new ArgumentNullException(nameof(array));
            if (array.Length < 4) throw new ArgumentException("Array must contain at least 4 elements.", nameof(array));
            X = array[0];
            Y = array[1];
            Z = array[2];
            W = array[3];
        }

        /// <summary>Initializes from a Double2 and Z, W components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Double2 xy, double z, double w) : this(xy.X, xy.Y, z, w) { }

        /// <summary>Initializes from X component, a Double2, and W component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double x, Double2 yz, double w) : this(x, yz.X, yz.Y, w) { }

        /// <summary>Initializes from X, Y components and a Double2.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double x, double y, Double2 zw) : this(x, y, zw.X, zw.Y) { }

        /// <summary>Initializes from two Double2 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Double2 xy, Double2 zw) : this(xy.X, xy.Y, zw.X, zw.Y) { }

        /// <summary>Initializes from a Double3 and W component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Double3 xyz, double w) : this(xyz.X, xyz.Y, xyz.Z, w) { }

        /// <summary>Initializes from X component and a Double3.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(double x, Double3 yzw) : this(x, yzw.X, yzw.Y, yzw.Z) { }

        // --- Type Conversion Constructors ---
        /// <summary>Initializes from a Float4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Float4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        /// <summary>Initializes from a Int4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Int4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        /// <summary>Initializes from a Byte4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Byte4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        /// <summary>Initializes from a UShort4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(UShort4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        /// <summary>Initializes from a UInt4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(UInt4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        /// <summary>Initializes from a ULong4 with type conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(ULong4 v) : this((double)v.X, (double)v.Y, (double)v.Z, (double)v.W) { }

        // --- Collection Constructors ---
        /// <summary>Initializes from an IEnumerable collection.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(IEnumerable<double> values)
        {
            var array = values.ToArray();
            if (array.Length < 4) throw new ArgumentException("Collection must contain at least 4 elements.", nameof(values));
            X = array[0];
            Y = array[1];
            Z = array[2];
            W = array[3];
        }

        /// <summary>Initializes from a ReadOnlySpan.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(ReadOnlySpan<double> span)
        {
            if (span.Length < 4) throw new ArgumentException("Span must contain at least 4 elements.", nameof(span));
            X = span[0];
            Y = span[1];
            Z = span[2];
            W = span[3];
        }

        /// <summary>Initializes from a Span.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double4(Span<double> span)
        {
            if (span.Length < 4) throw new ArgumentException("Span must contain at least 4 elements.", nameof(span));
            X = span[0];
            Y = span[1];
            Z = span[2];
            W = span[3];
        }

        // --- Static Properties ---
        /// <summary>Gets the zero vector.</summary>
        public static Double4 Zero { get { return new Double4(0.0, 0.0, 0.0, 0.0); } }
        /// <summary>Gets the one vector.</summary>
        public static Double4 One { get { return new Double4(1.0, 1.0, 1.0, 1.0); } }
        /// <summary>Gets the unit vector along the X-axis.</summary>
        public static Double4 UnitX { get { return new Double4(1.0, 0.0, 0.0, 0.0); } }
        /// <summary>Gets the unit vector along the Y-axis.</summary>
        public static Double4 UnitY { get { return new Double4(0.0, 1.0, 0.0, 0.0); } }
        /// <summary>Gets the unit vector along the Z-axis.</summary>
        public static Double4 UnitZ { get { return new Double4(0.0, 0.0, 1.0, 0.0); } }
        /// <summary>Gets the unit vector along the W-axis.</summary>
        public static Double4 UnitW { get { return new Double4(0.0, 0.0, 0.0, 1.0); } }

        // --- Properties ---
        /// <summary>Gets the magnitude (length) of the vector.</summary>
        public double Length
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return Math.Sqrt(LengthSquared); }
        }

        /// <summary>Gets the squared magnitude (length) of the vector.</summary>
        public double LengthSquared
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return X * X + Y * Y + Z * Z + W * W; }
        }

        /// <summary>Gets a normalized version of this vector.</summary>
        public Double4 Normalized
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                double lenSq = LengthSquared;
                if (lenSq <= double.Epsilon * double.Epsilon)
                {
                    return Zero;
                }
                double invLength = 1.0 / Math.Sqrt(lenSq);
                return new Double4(X * invLength, Y * invLength, Z * invLength, W * invLength);
            }
        }

        // --- Indexer ---
        /// <summary>Gets or sets the component at the specified index.</summary>
        public double this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                switch (index)
                {
                    case 0: return X;
                    case 1: return Y;
                    case 2: return Z;
                    case 3: return W;
                    default: throw new IndexOutOfRangeException(string.Format("Index must be between 0 and 3, but was {0}", index));
                }
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                switch (index)
                {
                    case 0: X = value; break;
                    case 1: Y = value; break;
                    case 2: Z = value; break;
                    case 3: W = value; break;
                    default: throw new IndexOutOfRangeException(string.Format("Index must be between 0 and 3, but was {0}", index));
                }
            }
        }

        // --- Vector-to-Vector Operators ---
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 a, Double4 b) { return new Double4(a.X + b.X, a.Y + b.Y, a.Z + b.Z, a.W + b.W); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 a, Double4 b) { return new Double4(a.X - b.X, a.Y - b.Y, a.Z - b.Z, a.W - b.W); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 a, Double4 b) { return new Double4(a.X * b.X, a.Y * b.Y, a.Z * b.Z, a.W * b.W); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 a, Double4 b) { return new Double4(a.X / b.X, a.Y / b.Y, a.Z / b.Z, a.W / b.W); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 a, Double4 b) { return new Double4(a.X % b.X, a.Y % b.Y, a.Z % b.Z, a.W % b.W); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v) { return new Double4(-v.X, -v.Y, -v.Z, -v.W); }

        // --- Scalar-Vector Operators ---
        /// <summary>float + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(float scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + float operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, float scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>float - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(float scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - float operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, float scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>float * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(float scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * float operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, float scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>float / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, float scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>float / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(float scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % float operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, float scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>float % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(float scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>double + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(double scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + double operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, double scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>double - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(double scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - double operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, double scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>double * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(double scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * double operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, double scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>double / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, double scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>double / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(double scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % double operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, double scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>double % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(double scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>int + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(int scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + int operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, int scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>int - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(int scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - int operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, int scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>int * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(int scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * int operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, int scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>int / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, int scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>int / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(int scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % int operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, int scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>int % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(int scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>byte + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(byte scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + byte operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, byte scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>byte - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(byte scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - byte operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, byte scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>byte * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(byte scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * byte operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, byte scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>byte / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, byte scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>byte / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(byte scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % byte operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, byte scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>byte % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(byte scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>ushort + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(ushort scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + ushort operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, ushort scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>ushort - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(ushort scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - ushort operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, ushort scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>ushort * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(ushort scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * ushort operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, ushort scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>ushort / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, ushort scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>ushort / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(ushort scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % ushort operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, ushort scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>ushort % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(ushort scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>uint + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(uint scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + uint operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, uint scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>uint - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(uint scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - uint operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, uint scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>uint * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(uint scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * uint operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, uint scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>uint / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, uint scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>uint / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(uint scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % uint operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, uint scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>uint % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(uint scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        /// <summary>ulong + Double4 operator. Vector components are (scalar + v.X, scalar + v.Y, scalar + v.Z, scalar + v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(ulong scalar, Double4 v)
        {
            return new Double4((double)(scalar + v.X), (double)(scalar + v.Y), (double)(scalar + v.Z), (double)(scalar + v.W));
        }

        /// <summary>Double4 + ulong operator. Vector components are (v.X + scalar, v.Y + scalar, v.Z + scalar, v.W + scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator +(Double4 v, ulong scalar)
        {
            return new Double4((double)(v.X + scalar), (double)(v.Y + scalar), (double)(v.Z + scalar), (double)(v.W + scalar));
        }

        /// <summary>ulong - Double4 operator. Vector components are (scalar - v.X, scalar - v.Y, scalar - v.Z, scalar - v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(ulong scalar, Double4 v)
        {
            return new Double4((double)(scalar - v.X), (double)(scalar - v.Y), (double)(scalar - v.Z), (double)(scalar - v.W));
        }

        /// <summary>Double4 - ulong operator. Vector components are (v.X - scalar, v.Y - scalar, v.Z - scalar, v.W - scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator -(Double4 v, ulong scalar)
        {
            return new Double4((double)(v.X - scalar), (double)(v.Y - scalar), (double)(v.Z - scalar), (double)(v.W - scalar));
        }

        /// <summary>ulong * Double4 operator. Vector components are (scalar * v.X, scalar * v.Y, scalar * v.Z, scalar * v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(ulong scalar, Double4 v)
        {
            return new Double4((double)(scalar * v.X), (double)(scalar * v.Y), (double)(scalar * v.Z), (double)(scalar * v.W));
        }

        /// <summary>Double4 * ulong operator. Vector components are (v.X * scalar, v.Y * scalar, v.Z * scalar, v.W * scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator *(Double4 v, ulong scalar)
        {
            return new Double4((double)(v.X * scalar), (double)(v.Y * scalar), (double)(v.Z * scalar), (double)(v.W * scalar));
        }

        /// <summary>ulong / Double4 operator. Vector components are (v.X / scalar, v.Y / scalar, v.Z / scalar, v.W / scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(Double4 v, ulong scalar)
        {
            return new Double4((double)(v.X / scalar), (double)(v.Y / scalar), (double)(v.Z / scalar), (double)(v.W / scalar));
        }

        /// <summary>ulong / Double4 operator. Vector components are (scalar / v.X, scalar / v.Y, scalar / v.Z, scalar / v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator /(ulong scalar, Double4 v)
        {
            return new Double4((double)(scalar / v.X), (double)(scalar / v.Y), (double)(scalar / v.Z), (double)(scalar / v.W));
        }

        /// <summary>Double4 % ulong operator. Vector components are (v.X % scalar, v.Y % scalar, v.Z % scalar, v.W % scalar).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(Double4 v, ulong scalar)
        {
            return new Double4((double)(v.X % scalar), (double)(v.Y % scalar), (double)(v.Z % scalar), (double)(v.W % scalar));
        }

        /// <summary>ulong % Double4 operator. Vector components are (scalar % v.X, scalar % v.Y, scalar % v.Z, scalar % v.W).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 operator %(ulong scalar, Double4 v)
        {
            return new Double4((double)(scalar % v.X), (double)(scalar % v.Y), (double)(scalar % v.Z), (double)(scalar % v.W));
        }

        // --- Component-wise Comparison Operators (Return Boolean Vector) ---
        /// <summary>Returns a Bool4 indicating the result of component-wise < comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <(Double4 a, Double4 b) { return new Bool4(a.X < b.X, a.Y < b.Y, a.Z < b.Z, a.W < b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise < comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <(Double4 a, double scalar) { return new Bool4(a.X < scalar, a.Y < scalar, a.Z < scalar, a.W < scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise < comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <(double scalar, Double4 a) { return new Bool4(scalar < a.X, scalar < a.Y, scalar < a.Z, scalar < a.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise <= comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <=(Double4 a, Double4 b) { return new Bool4(a.X <= b.X, a.Y <= b.Y, a.Z <= b.Z, a.W <= b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise <= comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <=(Double4 a, double scalar) { return new Bool4(a.X <= scalar, a.Y <= scalar, a.Z <= scalar, a.W <= scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise <= comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator <=(double scalar, Double4 a) { return new Bool4(scalar <= a.X, scalar <= a.Y, scalar <= a.Z, scalar <= a.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise > comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >(Double4 a, Double4 b) { return new Bool4(a.X > b.X, a.Y > b.Y, a.Z > b.Z, a.W > b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise > comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >(Double4 a, double scalar) { return new Bool4(a.X > scalar, a.Y > scalar, a.Z > scalar, a.W > scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise > comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >(double scalar, Double4 a) { return new Bool4(scalar > a.X, scalar > a.Y, scalar > a.Z, scalar > a.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise >= comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >=(Double4 a, Double4 b) { return new Bool4(a.X >= b.X, a.Y >= b.Y, a.Z >= b.Z, a.W >= b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise >= comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >=(Double4 a, double scalar) { return new Bool4(a.X >= scalar, a.Y >= scalar, a.Z >= scalar, a.W >= scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise >= comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator >=(double scalar, Double4 a) { return new Bool4(scalar >= a.X, scalar >= a.Y, scalar >= a.Z, scalar >= a.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise == comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator ==(Double4 a, Double4 b) { return new Bool4(a.X == b.X, a.Y == b.Y, a.Z == b.Z, a.W == b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise == comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator ==(Double4 a, double scalar) { return new Bool4(a.X == scalar, a.Y == scalar, a.Z == scalar, a.W == scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise == comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator ==(double scalar, Double4 a) { return new Bool4(scalar == a.X, scalar == a.Y, scalar == a.Z, scalar == a.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise != comparison.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator !=(Double4 a, Double4 b) { return new Bool4(a.X != b.X, a.Y != b.Y, a.Z != b.Z, a.W != b.W); }

        /// <summary>Returns a Bool4 indicating the result of component-wise != comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator !=(Double4 a, double scalar) { return new Bool4(a.X != scalar, a.Y != scalar, a.Z != scalar, a.W != scalar); }

        /// <summary>Returns a Bool4 indicating the result of component-wise != comparison with a scalar.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool4 operator !=(double scalar, Double4 a) { return new Bool4(scalar != a.X, scalar != a.Y, scalar != a.Z, scalar != a.W); }

        // --- Implicit Conversions ---
        /// <summary>Implicitly converts a Double2 to Double4 by adding default values for missing components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Double4(Double2 value) => new Double4(value.X, value.Y, 0.0, 0.0);

        /// <summary>Implicitly converts a Double3 to Double4 by adding default values for missing components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Double4(Double3 value) => new Double4(value.X, value.Y, value.Z, 0.0);

        /// <summary>Explicitly converts Double4 to Double2 by truncating components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Double2(Double4 value) => new Double2(value.X, value.Y);

        /// <summary>Explicitly converts Double4 to Double3 by truncating components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Double3(Double4 value) => new Double3(value.X, value.Y, value.Z);

        /// <summary>Explicitly converts Double4 to Float4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Float4(Double4 value) => new Float4((float)value.X, (float)value.Y, (float)value.Z, (float)value.W);

        /// <summary>Explicitly converts Double4 to Int4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Int4(Double4 value) => new Int4((int)value.X, (int)value.Y, (int)value.Z, (int)value.W);

        /// <summary>Explicitly converts Double4 to Byte4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Byte4(Double4 value) => new Byte4((byte)value.X, (byte)value.Y, (byte)value.Z, (byte)value.W);

        /// <summary>Explicitly converts Double4 to UShort4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator UShort4(Double4 value) => new UShort4((ushort)value.X, (ushort)value.Y, (ushort)value.Z, (ushort)value.W);

        /// <summary>Explicitly converts Double4 to UInt4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator UInt4(Double4 value) => new UInt4((uint)value.X, (uint)value.Y, (uint)value.Z, (uint)value.W);

        /// <summary>Explicitly converts Double4 to ULong4.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator ULong4(Double4 value) => new ULong4((ulong)value.X, (ulong)value.Y, (ulong)value.Z, (ulong)value.W);

        // --- Methods ---
        /// <summary>Returns a boolean vector indicating which components are less than the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 LessThan(Double4 other) { return new Bool4(X < other.X, Y < other.Y, Z < other.Z, W < other.W); }

        /// <summary>Returns a boolean vector indicating which components are less than or equal to the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 LessThanOrEqual(Double4 other) { return new Bool4(X <= other.X, Y <= other.Y, Z <= other.Z, W <= other.W); }

        /// <summary>Returns a boolean vector indicating which components are greater than the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 GreaterThan(Double4 other) { return new Bool4(X > other.X, Y > other.Y, Z > other.Z, W > other.W); }

        /// <summary>Returns a boolean vector indicating which components are greater than or equal to the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 GreaterThanOrEqual(Double4 other) { return new Bool4(X >= other.X, Y >= other.Y, Z >= other.Z, W >= other.W); }

        /// <summary>Selects components from two vectors based on a boolean mask.</summary>
        /// <param name="mask">Boolean vector mask for selection.</param>
        /// <param name="trueValue">Vector to select from when mask component is true.</param>
        /// <param name="falseValue">Vector to select from when mask component is false.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double4 Select(Bool4 mask, Double4 trueValue, Double4 falseValue)
        {
            return new Double4(mask.X ? trueValue.X : falseValue.X, mask.Y ? trueValue.Y : falseValue.Y, mask.Z ? trueValue.Z : falseValue.Z, mask.W ? trueValue.W : falseValue.W);
        }

        /// <summary>Returns a boolean vector indicating which components are within the specified range.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 InRange(Double4 min, Double4 max)
        {
            return new Bool4(X >= min.X && X <= max.X, Y >= min.Y && Y <= max.Y, Z >= min.Z && Z <= max.Z, W >= min.W && W <= max.W);
        }

        /// <summary>Returns a boolean vector indicating which components are equal to the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 EqualTo(Double4 other) { return new Bool4(X == other.X, Y == other.Y, Z == other.Z, W == other.W); }

        /// <summary>Returns a boolean vector indicating which components are not equal to the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 NotEqualTo(Double4 other) { return new Bool4(X != other.X, Y != other.Y, Z != other.Z, W != other.W); }

        /// <summary>Returns a boolean vector indicating which components are approximately equal to the corresponding components of another vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 ApproximatelyEqualTo(Double4 other) { return new Bool4(Math.Abs(X - other.X) <= double.Epsilon, Math.Abs(Y - other.Y) <= double.Epsilon, Math.Abs(Z - other.Z) <= double.Epsilon, Math.Abs(W - other.W) <= double.Epsilon); }

        /// <summary>Returns a boolean vector indicating which components are approximately equal to the corresponding components of another vector with a custom tolerance.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 ApproximatelyEqualTo(Double4 other, double tolerance)
        {
            return new Bool4(Math.Abs(X - other.X) <= tolerance, Math.Abs(Y - other.Y) <= tolerance, Math.Abs(Z - other.Z) <= tolerance, Math.Abs(W - other.W) <= tolerance);
        }

        /// <summary>Returns a boolean vector indicating which components are less than a scalar value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 LessThan(double scalar) { return new Bool4(X < scalar, Y < scalar, Z < scalar, W < scalar); }

        /// <summary>Returns a boolean vector indicating which components are greater than a scalar value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 GreaterThan(double scalar) { return new Bool4(X > scalar, Y > scalar, Z > scalar, W > scalar); }

        /// <summary>Returns a boolean vector indicating which components are equal to a scalar value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Bool4 EqualTo(double scalar) { return new Bool4(X == scalar, Y == scalar, Z == scalar, W == scalar); }

        /// <summary>Returns an array of components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double[] ToArray() { return new double[] { X, Y, Z, W }; }
        /// <summary>Returns an array of components.</summary>
        public override bool Equals(object obj) { return obj is Double4 && Equals((Double4)obj); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Double4 other) { return X == other.X && Y == other.Y && Z == other.Z && W == other.W; }

        public override int GetHashCode() { return X.GetHashCode() ^ (Y.GetHashCode() << 2) ^ (Z.GetHashCode() >> 2) ^ (W.GetHashCode() >> 1); }

        public override string ToString() { return ToString("G", CultureInfo.CurrentCulture); }

        public string ToString(string format) { return ToString(format, CultureInfo.CurrentCulture); }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            string separator = (formatProvider is CultureInfo) ? ((CultureInfo)formatProvider).TextInfo.ListSeparator : ", ";
            return "(" + X.ToString(format, formatProvider) + separator + Y.ToString(format, formatProvider) + separator + Z.ToString(format, formatProvider) + separator + W.ToString(format, formatProvider) + ")";
        }
    }
}
