//
// THIS FILE IS AUTO-GENERATED
//
// Do not modify this file directly. All changes will be lost when the code is regenerated.
// To make changes to this vector type, modify the SourceGenerator project and regenerate the code.
//
// Generated by: Prowl.Vector's SourceGenerator Console Application
// Date: 2025-05-14 10:56:39
//

using System;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using Prowl.Vector;

namespace Prowl.Vector
{
    /// <summary>A 2x2 matrix of doubles.</summary>
    [System.Serializable]
    public partial struct Double2x2 : System.IEquatable<Double2x2>, IFormattable
    {
        /// <summary>Column 0 of the matrix.</summary>
        public Double2 c0;
        /// <summary>Column 1 of the matrix.</summary>
        public Double2 c1;

        /// <summary>Double2x2 identity transform.</summary>
        public static readonly Double2x2 Identity = new Double2x2(new Double2(1.0, 0.0), new Double2(0.0, 1.0));

        /// <summary>Double2x2 zero value.</summary>
        public static readonly Double2x2 Zero = new Double2x2(Double2.Zero, Double2.Zero);

        /// <summary>Constructs a Double2x2 matrix from 2 Double2 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double2x2(Double2 col0, Double2 col1)
        {
            this.c0 = col0;
            this.c1 = col1;
        }

        /// <summary>Constructs a Double2x2 matrix from 4 double values given in row-major order.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double2x2(double m00, double m01, double m10, double m11)
        {
            this.c0 = new Double2(m00, m10);
            this.c1 = new Double2(m01, m11);
        }

        /// <summary>Constructs a Double2x2 matrix from a single double value by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Double2x2(double v)
        {
            this.c0 = new Double2(v);
            this.c1 = new Double2(v);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator +(Double2x2 lhs, Double2x2 rhs) { return new Double2x2(lhs.c0 + rhs.c0, lhs.c1 + rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator +(Double2x2 lhs, double rhs) { return new Double2x2(lhs.c0 + rhs, lhs.c1 + rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator +(double lhs, Double2x2 rhs) { return new Double2x2(lhs + rhs.c0, lhs + rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator -(Double2x2 lhs, Double2x2 rhs) { return new Double2x2(lhs.c0 - rhs.c0, lhs.c1 - rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator -(Double2x2 lhs, double rhs) { return new Double2x2(lhs.c0 - rhs, lhs.c1 - rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator -(double lhs, Double2x2 rhs) { return new Double2x2(lhs - rhs.c0, lhs - rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator /(Double2x2 lhs, Double2x2 rhs) { return new Double2x2(lhs.c0 / rhs.c0, lhs.c1 / rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator /(Double2x2 lhs, double rhs) { return new Double2x2(lhs.c0 / rhs, lhs.c1 / rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator /(double lhs, Double2x2 rhs) { return new Double2x2(lhs / rhs.c0, lhs / rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator %(Double2x2 lhs, Double2x2 rhs) { return new Double2x2(lhs.c0 % rhs.c0, lhs.c1 % rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator %(Double2x2 lhs, double rhs) { return new Double2x2(lhs.c0 % rhs, lhs.c1 % rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator %(double lhs, Double2x2 rhs) { return new Double2x2(lhs % rhs.c0, lhs % rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator -(Double2x2 val) { return new Double2x2(-val.c0, -val.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 < rhs.c0, lhs.c1 < rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 < rhs, lhs.c1 < rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <(double lhs, Double2x2 rhs) { return new Bool2x2(lhs < rhs.c0, lhs < rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <=(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <=(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 <= rhs, lhs.c1 <= rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator <=(double lhs, Double2x2 rhs) { return new Bool2x2(lhs <= rhs.c0, lhs <= rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 > rhs.c0, lhs.c1 > rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 > rhs, lhs.c1 > rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >(double lhs, Double2x2 rhs) { return new Bool2x2(lhs > rhs.c0, lhs > rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >=(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >=(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 >= rhs, lhs.c1 >= rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator >=(double lhs, Double2x2 rhs) { return new Bool2x2(lhs >= rhs.c0, lhs >= rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator ==(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 == rhs.c0, lhs.c1 == rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator ==(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 == rhs, lhs.c1 == rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator ==(double lhs, Double2x2 rhs) { return new Bool2x2(lhs == rhs.c0, lhs == rhs.c1); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator !=(Double2x2 lhs, Double2x2 rhs) { return new Bool2x2(lhs.c0 != rhs.c0, lhs.c1 != rhs.c1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator !=(Double2x2 lhs, double rhs) { return new Bool2x2(lhs.c0 != rhs, lhs.c1 != rhs); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bool2x2 operator !=(double lhs, Double2x2 rhs) { return new Bool2x2(lhs != rhs.c0, lhs != rhs.c1); }

        /// <summary>Returns the product of two Double2x2 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double2x2 operator *(Double2x2 lhs, Double2x2 rhs)
        {
            return new Double2x2(
                new Double2((lhs.c0.X * rhs.c0.X + lhs.c1.X * rhs.c0.Y), (lhs.c0.Y * rhs.c0.X + lhs.c1.Y * rhs.c0.Y)),
                new Double2((lhs.c0.X * rhs.c1.X + lhs.c1.X * rhs.c1.Y), (lhs.c0.Y * rhs.c1.X + lhs.c1.Y * rhs.c1.Y))
            );
        }

        /// <summary>Returns a reference to the Double2 (column) at a specified index.</summary>
        unsafe public ref Double2 this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                if ((uint)index >= 2)
                    throw new System.ArgumentOutOfRangeException(nameof(index), $"Column index must be between 0 and 1, but was {index}.");

                fixed (Double2* pC0 = &this.c0)
                {
                    return ref pC0[index];
                }
            }
        }

        /// <summary>Returns the element at row and column indices.</summary>
        public double this[int row, int column]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                if ((uint)column >= 2)
                    throw new System.ArgumentOutOfRangeException(nameof(column));
                return this[column][row];
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                if ((uint)column >= 2)
                    throw new System.ArgumentOutOfRangeException(nameof(column));
                var temp = this[column];
                temp[row] = value;
                this[column] = temp;
            }
        }
        /// <summary>Returns an array of components.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double[] ToArray()
        {
            double[] array = new double[4];
            for (int i = 0; i < 2; i++)
                for (int j = 0; j < 2; j++)
                    array[i * 2 + j] = this[i, j];
            return array;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Double2x2 rhs) { return this.c0.Equals(rhs.c0) && this.c1.Equals(rhs.c1); }

        public override bool Equals(object o) { return o is Double2x2 converted && Equals(converted); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hash = 17;
                hash = hash * 23 + c0.GetHashCode();
                hash = hash * 23 + c1.GetHashCode();
                return hash;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString() { return ToString(null, CultureInfo.CurrentCulture); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format) { return ToString(format, CultureInfo.CurrentCulture); }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("Double2x2(");
            sb.Append(this.c0.X.ToString(format, formatProvider));
            sb.Append(", ");
            sb.Append(this.c1.X.ToString(format, formatProvider));
            sb.Append(", ");
            sb.Append("  ");
            sb.Append(this.c0.Y.ToString(format, formatProvider));
            sb.Append(", ");
            sb.Append(this.c1.Y.ToString(format, formatProvider));
            sb.Append(")");
            return sb.ToString();
        }

    }
}
