//
// THIS FILE IS AUTO-GENERATED
//
// Do not modify this file directly. All changes will be lost when the code is regenerated.
// To make changes to this vector type, modify the SourceGenerator project and regenerate the code.
//
// Generated by: Prowl.Vector's SourceGenerator Console Application
// Date: 2025-10-10 14:02:57
//

using System; 
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using Prowl.Vector;

namespace Prowl.Vector
{

/// <summary>A 3x2 matrix of floats.</summary>
[System.Serializable]
public partial struct Float3x2 : System.IEquatable<Float3x2>, IFormattable
{
	/// <summary>Column 0 of the matrix.</summary>
	public Float3 c0;
	/// <summary>Column 1 of the matrix.</summary>
	public Float3 c1;

	/// <summary>Float3x2 zero value.</summary>
	public static readonly Float3x2 Zero = new Float3x2(Float3.Zero, Float3.Zero);

	/// <summary>Constructs a Float3x2 matrix from 2 Float3 vectors.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(Float3 col0, Float3 col1)
	{
		this.c0 = col0;
		this.c1 = col1;
	}

	/// <summary>Constructs a Float3x2 matrix from 6 float values given in row-major order.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(float m00, float m01, float m10, float m11, float m20, float m21)
	{
		this.c0 = new Float3(m00, m10, m20);
		this.c1 = new Float3(m01, m11, m21);
	}

	/// <summary>Constructs a Float3x2 matrix from a single float value by assigning it to every component.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(float v)
	{
		this.c0 = new Float3(v);
		this.c1 = new Float3(v);
	}

	/// <summary>Constructs a Float3x2 from a Double3x2 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(Double3x2 m)
	{
		this.c0 = new Float3(m.c0);
		this.c1 = new Float3(m.c1);
	}

	/// <summary>Constructs a Float3x2 from a Int3x2 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(Int3x2 m)
	{
		this.c0 = new Float3(m.c0);
		this.c1 = new Float3(m.c1);
	}

	/// <summary>Constructs a Float3x2 from a UInt3x2 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float3x2(UInt3x2 m)
	{
		this.c0 = new Float3(m.c0);
		this.c1 = new Float3(m.c1);
	}

	/// <summary>Returns a reference to the Float3 (column) at a specified index.</summary>
	unsafe public ref Float3 this[int index]
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get
		{
			if ((uint)index >= 2)
				throw new System.ArgumentOutOfRangeException(nameof(index), $"Column index must be between 0 and 1, but was {index}.");

			fixed (Float3* pC0 = &this.c0)
			{
				return ref pC0[index];
			}
		}
	}

	/// <summary>Returns the element at row and column indices.</summary>
	public float this[int row, int column]
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get
		{
			if ((uint)column >= 2)
				throw new System.ArgumentOutOfRangeException(nameof(column));
			return this[column][row];
		}
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		set
		{
			if ((uint)column >= 2)
				throw new System.ArgumentOutOfRangeException(nameof(column));
			var temp = this[column];
			temp[row] = value;
			this[column] = temp;
		}
	}
	// --- Component-wise Operators ---
	/// <summary>Returns the component-wise + of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator +(Float3x2 lhs, Float3x2 rhs) => new Float3x2(lhs.c0 + rhs.c0, lhs.c1 + rhs.c1);

	/// <summary>Returns the component-wise + of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator +(Float3x2 lhs, float rhs) => new Float3x2(lhs.c0 + rhs, lhs.c1 + rhs);

	/// <summary>Returns the component-wise + of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator +(float lhs, Float3x2 rhs) => new Float3x2(lhs + rhs.c0, lhs + rhs.c1);

	/// <summary>Returns the component-wise - of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator -(Float3x2 lhs, Float3x2 rhs) => new Float3x2(lhs.c0 - rhs.c0, lhs.c1 - rhs.c1);

	/// <summary>Returns the component-wise - of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator -(Float3x2 lhs, float rhs) => new Float3x2(lhs.c0 - rhs, lhs.c1 - rhs);

	/// <summary>Returns the component-wise - of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator -(float lhs, Float3x2 rhs) => new Float3x2(lhs - rhs.c0, lhs - rhs.c1);

	/// <summary>Returns the component-wise * of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator *(Float3x2 lhs, Float3x2 rhs) => new Float3x2(lhs.c0 * rhs.c0, lhs.c1 * rhs.c1);

	/// <summary>Returns the component-wise * of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator *(Float3x2 lhs, float rhs) => new Float3x2(lhs.c0 * rhs, lhs.c1 * rhs);

	/// <summary>Returns the component-wise * of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator *(float lhs, Float3x2 rhs) => new Float3x2(lhs * rhs.c0, lhs * rhs.c1);

	/// <summary>Returns the component-wise / of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator /(Float3x2 lhs, Float3x2 rhs) => new Float3x2(lhs.c0 / rhs.c0, lhs.c1 / rhs.c1);

	/// <summary>Returns the component-wise / of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator /(Float3x2 lhs, float rhs) => new Float3x2(lhs.c0 / rhs, lhs.c1 / rhs);

	/// <summary>Returns the component-wise / of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator /(float lhs, Float3x2 rhs) => new Float3x2(lhs / rhs.c0, lhs / rhs.c1);

	/// <summary>Returns the component-wise % of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator %(Float3x2 lhs, Float3x2 rhs) => new Float3x2(lhs.c0 % rhs.c0, lhs.c1 % rhs.c1);

	/// <summary>Returns the component-wise % of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator %(Float3x2 lhs, float rhs) => new Float3x2(lhs.c0 % rhs, lhs.c1 % rhs);

	/// <summary>Returns the component-wise % of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator %(float lhs, Float3x2 rhs) => new Float3x2(lhs % rhs.c0, lhs % rhs.c1);

	/// <summary>Returns the component-wise negation of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float3x2 operator -(Float3x2 val) => new Float3x2(-val.c0, -val.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise < comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 < rhs.c0, lhs.c1 < rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise < comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 < rhs, lhs.c1 < rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise < comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <(float lhs, Float3x2 rhs) => new Bool3x2(lhs < rhs.c0, lhs < rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise <= comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <=(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise <= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <=(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 <= rhs, lhs.c1 <= rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise <= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator <=(float lhs, Float3x2 rhs) => new Bool3x2(lhs <= rhs.c0, lhs <= rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise > comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 > rhs.c0, lhs.c1 > rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise > comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 > rhs, lhs.c1 > rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise > comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >(float lhs, Float3x2 rhs) => new Bool3x2(lhs > rhs.c0, lhs > rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise >= comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >=(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise >= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >=(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 >= rhs, lhs.c1 >= rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise >= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator >=(float lhs, Float3x2 rhs) => new Bool3x2(lhs >= rhs.c0, lhs >= rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise == comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator ==(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 == rhs.c0, lhs.c1 == rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise == comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator ==(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 == rhs, lhs.c1 == rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise == comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator ==(float lhs, Float3x2 rhs) => new Bool3x2(lhs == rhs.c0, lhs == rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise != comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator !=(Float3x2 lhs, Float3x2 rhs) => new Bool3x2(lhs.c0 != rhs.c0, lhs.c1 != rhs.c1);

	/// <summary>Returns a Bool3x2 indicating component-wise != comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator !=(Float3x2 lhs, float rhs) => new Bool3x2(lhs.c0 != rhs, lhs.c1 != rhs);

	/// <summary>Returns a Bool3x2 indicating component-wise != comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool3x2 operator !=(float lhs, Float3x2 rhs) => new Bool3x2(lhs != rhs.c0, lhs != rhs.c1);

	// --- Cross-Type Casting Operators ---
	/// <summary>Explicitly converts a Double3x2 to a Float3x2.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static explicit operator Float3x2(Double3x2 m)
	{
		return new Float3x2((Float3)m.c0, (Float3)m.c1);
	}

	/// <summary>Implicitly converts a Int3x2 to a Float3x2.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float3x2(Int3x2 m)
	{
		return new Float3x2((Float3)m.c0, (Float3)m.c1);
	}

	/// <summary>Implicitly converts a UInt3x2 to a Float3x2.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float3x2(UInt3x2 m)
	{
		return new Float3x2((Float3)m.c0, (Float3)m.c1);
	}

	// --- System.Numerics Conversions ---
	/// <summary>Implicitly converts this Float3x2 to a System.Numerics.Matrix3x2.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator System.Numerics.Matrix3x2(Float3x2 m)
	{
		return new System.Numerics.Matrix3x2(
			m.c0.X, m.c1.X,
			m.c0.Y, m.c1.Y,
			m.c0.Z, m.c1.Z);
	}

	/// <summary>Implicitly converts a System.Numerics.Matrix3x2 to this Float3x2.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float3x2(System.Numerics.Matrix3x2 m)
	{
		return new Float3x2(
			m.M11, m.M12,
			m.M21, m.M22,
			m.M31, m.M32);
	}

	// --- Matrix Methods ---
	/// <summary>Gets the transpose of this matrix.</summary>
	public Float2x3 Transpose
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Maths.Transpose(this);
	}

	/// <summary>Gets row 0 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float2 GetRow0()
	{
		return new Float2(c0.X, c1.X);
	}

	/// <summary>Sets row 0 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow0(Float2 value)
	{
		c0.X = value.X;
		c1.X = value.Y;
	}

	/// <summary>Gets row 1 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float2 GetRow1()
	{
		return new Float2(c0.Y, c1.Y);
	}

	/// <summary>Sets row 1 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow1(Float2 value)
	{
		c0.Y = value.X;
		c1.Y = value.Y;
	}

	/// <summary>Gets row 2 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Float2 GetRow2()
	{
		return new Float2(c0.Z, c1.Z);
	}

	/// <summary>Sets row 2 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow2(Float2 value)
	{
		c0.Z = value.X;
		c1.Z = value.Y;
	}

	/// <summary>Returns an array of components.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public float[] ToArray()
	{
		float[] array = new float[6];
		for (int i = 0; i < 3; i++)
			for (int j = 0; j < 2; j++)
				array[i * 2 + j] = this[i, j];
		return array;
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool Equals(Float3x2 rhs) { return this.c0.Equals(rhs.c0) && this.c1.Equals(rhs.c1); }

	public override bool Equals(object? o) { return o is Float3x2 converted && Equals(converted); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hash = 17;
			hash = hash * 23 + c0.GetHashCode();
			hash = hash * 23 + c1.GetHashCode();
			return hash;
		}
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override string ToString() { return ToString(null, CultureInfo.CurrentCulture); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string format) { return ToString(format, CultureInfo.CurrentCulture); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string format, IFormatProvider formatProvider)
	{
		StringBuilder sb = new StringBuilder();
		sb.Append("Float3x2(");
		sb.Append(this.c0.X.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.X.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append("  ");
		sb.Append(this.c0.Y.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.Y.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append("  ");
		sb.Append(this.c0.Z.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.Z.ToString(format, formatProvider));
		sb.Append(")");
		return sb.ToString();
	}

}
}
