//
// THIS FILE IS AUTO-GENERATED
//
// Do not modify this file directly. All changes will be lost when the code is regenerated.
// To make changes to this vector type, modify the SourceGenerator project and regenerate the code.
//
// Generated by: Prowl.Vector's SourceGenerator Console Application
// Date: 2025-10-10 14:02:57
//

using System; 
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using Prowl.Vector;

namespace Prowl.Vector
{

/// <summary>A 4x3 matrix of uints.</summary>
[System.Serializable]
public partial struct UInt4x3 : System.IEquatable<UInt4x3>, IFormattable
{
	/// <summary>Column 0 of the matrix.</summary>
	public UInt4 c0;
	/// <summary>Column 1 of the matrix.</summary>
	public UInt4 c1;
	/// <summary>Column 2 of the matrix.</summary>
	public UInt4 c2;

	/// <summary>UInt4x3 zero value.</summary>
	public static readonly UInt4x3 Zero = new UInt4x3(UInt4.Zero, UInt4.Zero, UInt4.Zero);

	/// <summary>Constructs a UInt4x3 matrix from 3 UInt4 vectors.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(UInt4 col0, UInt4 col1, UInt4 col2)
	{
		this.c0 = col0;
		this.c1 = col1;
		this.c2 = col2;
	}

	/// <summary>Constructs a UInt4x3 matrix from 12 uint values given in row-major order.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(uint m00, uint m01, uint m02, uint m10, uint m11, uint m12, uint m20, uint m21, uint m22, uint m30, uint m31, uint m32)
	{
		this.c0 = new UInt4(m00, m10, m20, m30);
		this.c1 = new UInt4(m01, m11, m21, m31);
		this.c2 = new UInt4(m02, m12, m22, m32);
	}

	/// <summary>Constructs a UInt4x3 matrix from a single uint value by assigning it to every component.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(uint v)
	{
		this.c0 = new UInt4(v);
		this.c1 = new UInt4(v);
		this.c2 = new UInt4(v);
	}

	/// <summary>Constructs a UInt4x3 from a Float4x3 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(Float4x3 m)
	{
		this.c0 = new UInt4(m.c0);
		this.c1 = new UInt4(m.c1);
		this.c2 = new UInt4(m.c2);
	}

	/// <summary>Constructs a UInt4x3 from a Double4x3 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(Double4x3 m)
	{
		this.c0 = new UInt4(m.c0);
		this.c1 = new UInt4(m.c1);
		this.c2 = new UInt4(m.c2);
	}

	/// <summary>Constructs a UInt4x3 from a Int4x3 with type conversion.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt4x3(Int4x3 m)
	{
		this.c0 = new UInt4(m.c0);
		this.c1 = new UInt4(m.c1);
		this.c2 = new UInt4(m.c2);
	}

	/// <summary>Returns a reference to the UInt4 (column) at a specified index.</summary>
	unsafe public ref UInt4 this[int index]
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get
		{
			if ((uint)index >= 3)
				throw new System.ArgumentOutOfRangeException(nameof(index), $"Column index must be between 0 and 2, but was {index}.");

			fixed (UInt4* pC0 = &this.c0)
			{
				return ref pC0[index];
			}
		}
	}

	/// <summary>Returns the element at row and column indices.</summary>
	public uint this[int row, int column]
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get
		{
			if ((uint)column >= 3)
				throw new System.ArgumentOutOfRangeException(nameof(column));
			return this[column][row];
		}
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		set
		{
			if ((uint)column >= 3)
				throw new System.ArgumentOutOfRangeException(nameof(column));
			var temp = this[column];
			temp[row] = value;
			this[column] = temp;
		}
	}
	// --- Component-wise Operators ---
	/// <summary>Returns the component-wise + of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator +(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 + rhs.c0, lhs.c1 + rhs.c1, lhs.c2 + rhs.c2);

	/// <summary>Returns the component-wise + of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator +(UInt4x3 lhs, uint rhs) => new UInt4x3(lhs.c0 + rhs, lhs.c1 + rhs, lhs.c2 + rhs);

	/// <summary>Returns the component-wise + of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator +(uint lhs, UInt4x3 rhs) => new UInt4x3(lhs + rhs.c0, lhs + rhs.c1, lhs + rhs.c2);

	/// <summary>Returns the component-wise - of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator -(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 - rhs.c0, lhs.c1 - rhs.c1, lhs.c2 - rhs.c2);

	/// <summary>Returns the component-wise - of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator -(UInt4x3 lhs, uint rhs) => new UInt4x3(lhs.c0 - rhs, lhs.c1 - rhs, lhs.c2 - rhs);

	/// <summary>Returns the component-wise - of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator -(uint lhs, UInt4x3 rhs) => new UInt4x3(lhs - rhs.c0, lhs - rhs.c1, lhs - rhs.c2);

	/// <summary>Returns the component-wise * of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator *(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 * rhs.c0, lhs.c1 * rhs.c1, lhs.c2 * rhs.c2);

	/// <summary>Returns the component-wise * of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator *(UInt4x3 lhs, uint rhs) => new UInt4x3(lhs.c0 * rhs, lhs.c1 * rhs, lhs.c2 * rhs);

	/// <summary>Returns the component-wise * of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator *(uint lhs, UInt4x3 rhs) => new UInt4x3(lhs * rhs.c0, lhs * rhs.c1, lhs * rhs.c2);

	/// <summary>Returns the component-wise / of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator /(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 / rhs.c0, lhs.c1 / rhs.c1, lhs.c2 / rhs.c2);

	/// <summary>Returns the component-wise / of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator /(UInt4x3 lhs, uint rhs) => new UInt4x3(lhs.c0 / rhs, lhs.c1 / rhs, lhs.c2 / rhs);

	/// <summary>Returns the component-wise / of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator /(uint lhs, UInt4x3 rhs) => new UInt4x3(lhs / rhs.c0, lhs / rhs.c1, lhs / rhs.c2);

	/// <summary>Returns the component-wise % of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator %(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 % rhs.c0, lhs.c1 % rhs.c1, lhs.c2 % rhs.c2);

	/// <summary>Returns the component-wise % of matrix and scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator %(UInt4x3 lhs, uint rhs) => new UInt4x3(lhs.c0 % rhs, lhs.c1 % rhs, lhs.c2 % rhs);

	/// <summary>Returns the component-wise % of scalar and matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator %(uint lhs, UInt4x3 rhs) => new UInt4x3(lhs % rhs.c0, lhs % rhs.c1, lhs % rhs.c2);

	/// <summary>Returns the component-wise & of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator &(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 & rhs.c0, lhs.c1 & rhs.c1, lhs.c2 & rhs.c2);

	/// <summary>Returns the component-wise | of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator |(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 | rhs.c0, lhs.c1 | rhs.c1, lhs.c2 | rhs.c2);

	/// <summary>Returns the component-wise ^ of two matrices.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator ^(UInt4x3 lhs, UInt4x3 rhs) => new UInt4x3(lhs.c0 ^ rhs.c0, lhs.c1 ^ rhs.c1, lhs.c2 ^ rhs.c2);

	/// <summary>Returns the component-wise << of matrix by scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator <<(UInt4x3 lhs, int rhs) => new UInt4x3(lhs.c0 << rhs, lhs.c1 << rhs, lhs.c2 << rhs);

	/// <summary>Returns the component-wise >> of matrix by scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator >>(UInt4x3 lhs, int rhs) => new UInt4x3(lhs.c0 >> rhs, lhs.c1 >> rhs, lhs.c2 >> rhs);

	/// <summary>Returns the component-wise bitwise NOT of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static UInt4x3 operator ~(UInt4x3 val) => new UInt4x3(~val.c0, ~val.c1, ~val.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise < comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 < rhs.c0, lhs.c1 < rhs.c1, lhs.c2 < rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise < comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 < rhs, lhs.c1 < rhs, lhs.c2 < rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise < comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs < rhs.c0, lhs < rhs.c1, lhs < rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise <= comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <=(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1, lhs.c2 <= rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise <= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <=(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 <= rhs, lhs.c1 <= rhs, lhs.c2 <= rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise <= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator <=(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs <= rhs.c0, lhs <= rhs.c1, lhs <= rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise > comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 > rhs.c0, lhs.c1 > rhs.c1, lhs.c2 > rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise > comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 > rhs, lhs.c1 > rhs, lhs.c2 > rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise > comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs > rhs.c0, lhs > rhs.c1, lhs > rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise >= comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >=(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1, lhs.c2 >= rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise >= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >=(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 >= rhs, lhs.c1 >= rhs, lhs.c2 >= rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise >= comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator >=(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs >= rhs.c0, lhs >= rhs.c1, lhs >= rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise == comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator ==(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 == rhs.c0, lhs.c1 == rhs.c1, lhs.c2 == rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise == comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator ==(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 == rhs, lhs.c1 == rhs, lhs.c2 == rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise == comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator ==(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs == rhs.c0, lhs == rhs.c1, lhs == rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise != comparison.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator !=(UInt4x3 lhs, UInt4x3 rhs) => new Bool4x3(lhs.c0 != rhs.c0, lhs.c1 != rhs.c1, lhs.c2 != rhs.c2);

	/// <summary>Returns a Bool4x3 indicating component-wise != comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator !=(UInt4x3 lhs, uint rhs) => new Bool4x3(lhs.c0 != rhs, lhs.c1 != rhs, lhs.c2 != rhs);

	/// <summary>Returns a Bool4x3 indicating component-wise != comparison with scalar.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Bool4x3 operator !=(uint lhs, UInt4x3 rhs) => new Bool4x3(lhs != rhs.c0, lhs != rhs.c1, lhs != rhs.c2);

	// --- Cross-Type Casting Operators ---
	/// <summary>Explicitly converts a Float4x3 to a UInt4x3.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static explicit operator UInt4x3(Float4x3 m)
	{
		return new UInt4x3((UInt4)m.c0, (UInt4)m.c1, (UInt4)m.c2);
	}

	/// <summary>Explicitly converts a Double4x3 to a UInt4x3.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static explicit operator UInt4x3(Double4x3 m)
	{
		return new UInt4x3((UInt4)m.c0, (UInt4)m.c1, (UInt4)m.c2);
	}

	/// <summary>Explicitly converts a Int4x3 to a UInt4x3.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static explicit operator UInt4x3(Int4x3 m)
	{
		return new UInt4x3((UInt4)m.c0, (UInt4)m.c1, (UInt4)m.c2);
	}

	// --- Matrix Methods ---
	/// <summary>Gets the transpose of this matrix.</summary>
	public UInt3x4 Transpose
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Maths.Transpose(this);
	}

	/// <summary>Gets row 0 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt3 GetRow0()
	{
		return new UInt3(c0.X, c1.X, c2.X);
	}

	/// <summary>Sets row 0 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow0(UInt3 value)
	{
		c0.X = value.X;
		c1.X = value.Y;
		c2.X = value.Z;
	}

	/// <summary>Gets row 1 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt3 GetRow1()
	{
		return new UInt3(c0.Y, c1.Y, c2.Y);
	}

	/// <summary>Sets row 1 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow1(UInt3 value)
	{
		c0.Y = value.X;
		c1.Y = value.Y;
		c2.Y = value.Z;
	}

	/// <summary>Gets row 2 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt3 GetRow2()
	{
		return new UInt3(c0.Z, c1.Z, c2.Z);
	}

	/// <summary>Sets row 2 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow2(UInt3 value)
	{
		c0.Z = value.X;
		c1.Z = value.Y;
		c2.Z = value.Z;
	}

	/// <summary>Gets row 3 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public UInt3 GetRow3()
	{
		return new UInt3(c0.W, c1.W, c2.W);
	}

	/// <summary>Sets row 3 of the matrix.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void SetRow3(UInt3 value)
	{
		c0.W = value.X;
		c1.W = value.Y;
		c2.W = value.Z;
	}

	/// <summary>Returns an array of components.</summary>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public uint[] ToArray()
	{
		uint[] array = new uint[12];
		for (int i = 0; i < 4; i++)
			for (int j = 0; j < 3; j++)
				array[i * 3 + j] = this[i, j];
		return array;
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool Equals(UInt4x3 rhs) { return this.c0.Equals(rhs.c0) && this.c1.Equals(rhs.c1) && this.c2.Equals(rhs.c2); }

	public override bool Equals(object? o) { return o is UInt4x3 converted && Equals(converted); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hash = 17;
			hash = hash * 23 + c0.GetHashCode();
			hash = hash * 23 + c1.GetHashCode();
			hash = hash * 23 + c2.GetHashCode();
			return hash;
		}
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override string ToString() { return ToString(null, CultureInfo.CurrentCulture); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string format) { return ToString(format, CultureInfo.CurrentCulture); }

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string format, IFormatProvider formatProvider)
	{
		StringBuilder sb = new StringBuilder();
		sb.Append("UInt4x3(");
		sb.Append(this.c0.X.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.X.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c2.X.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append("  ");
		sb.Append(this.c0.Y.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.Y.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c2.Y.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append("  ");
		sb.Append(this.c0.Z.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.Z.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c2.Z.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append("  ");
		sb.Append(this.c0.W.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c1.W.ToString(format, formatProvider));
		sb.Append(", ");
		sb.Append(this.c2.W.ToString(format, formatProvider));
		sb.Append(")");
		return sb.ToString();
	}

}
}
